-- Seeds the 87 classes the MobileNetV3 classifier predicts.
--
-- model_label is the exact string from ml/idx_to_class.json. It is the join key
-- between a vision prediction and the catalog: OnnxVisionClassifier returns a
-- label, and ToolCategoryRepository.findByModelLabel resolves it to a row here.
-- Changing a model_label here without retraining silently breaks that lookup.
--
-- display_name is the human-facing name shown in the storefront and used by Piper
-- in conversation. synonyms is intentionally left empty - populate it as real
-- customer phrasing shows up in chat logs, rather than guessing up front.

INSERT INTO tool_category (model_label, display_name) VALUES
    ('air_compressors', 'Air Compressor'),
    ('angle_grinder', 'Angle Grinder'),
    ('axe_ai', 'Axe'),
    ('ball_valve', 'Ball Valve'),
    ('bearing', 'Bearing'),
    ('caulking_gun', 'Caulking Gun'),
    ('chisel', 'Chisel'),
    ('clamp', 'Clamp'),
    ('concrete_mixer', 'Concrete Mixer'),
    ('construction_earmuffs', 'Construction Earmuffs'),
    ('corner_trowel', 'Corner Trowel'),
    ('crowbar', 'Crowbar'),
    ('digital_caliper', 'Digital Caliper'),
    ('digital_torque_wrench', 'Digital Torque Wrench'),
    ('drill_bit_ai', 'Drill Bit'),
    ('ear_plugs', 'Ear Plugs'),
    ('electric_drill_ai', 'Electric Drill'),
    ('extension_cord', 'Extension Cord'),
    ('extension_spring', 'Extension Spring'),
    ('file_tool', 'File'),
    ('fire_extinguisher', 'Fire Extinguisher'),
    ('first_aid_kit', 'First Aid Kit'),
    ('flashlight', 'Flashlight'),
    ('float_tool', 'Float'),
    ('generator', 'Generator'),
    ('glue_gun_ai', 'Glue Gun'),
    ('hacksaw', 'Hacksaw'),
    ('hammer_ai', 'Hammer'),
    ('hand_saw_ai', 'Hand Saw'),
    ('head_flashlight', 'Head Flashlight'),
    ('heat_gun', 'Heat Gun'),
    ('heavy_duty_vacuum_cleaner', 'Heavy-Duty Vacuum Cleaner'),
    ('hoe_tool', 'Hoe'),
    ('infrared_digital_thermometer', 'Infrared Digital Thermometer'),
    ('jack_hammer', 'Jackhammer'),
    ('jack_plane', 'Jack Plane'),
    ('jigsaw', 'Jigsaw'),
    ('kneepads', 'Kneepads'),
    ('ladder', 'Ladder'),
    ('led_light_bulb', 'LED Light Bulb'),
    ('level_tool', 'Level'),
    ('machete', 'Machete'),
    ('mallet', 'Mallet'),
    ('masking_tape_roll', 'Masking Tape Roll'),
    ('measuring_wheel', 'Measuring Wheel'),
    ('metal_nut', 'Metal Nut'),
    ('moisture_meter', 'Moisture Meter'),
    ('nail_ai', 'Nail'),
    ('nail_gun', 'Nail Gun'),
    ('paint_brush', 'Paint Brush'),
    ('paint_respirator', 'Paint Respirator'),
    ('paint_roller_ai', 'Paint Roller'),
    ('paint_spray_gun', 'Paint Spray Gun'),
    ('paint_tray', 'Paint Tray'),
    ('palm_sander', 'Palm Sander'),
    ('plastic_bucket', 'Plastic Bucket'),
    ('pliers_ai', 'Pliers'),
    ('plunger', 'Plunger'),
    ('power_socket', 'Power Socket'),
    ('pry_bar', 'Pry Bar'),
    ('putty_knife', 'Putty Knife'),
    ('respirator_mask_n95', 'N95 Respirator Mask'),
    ('rubber_boots', 'Rubber Boots'),
    ('rubber_gloves', 'Rubber Gloves'),
    ('safety_glasses', 'Safety Glasses'),
    ('safety_helmet', 'Safety Helmet'),
    ('safety_vest', 'Safety Vest'),
    ('screwdriver_ai', 'Screwdriver'),
    ('socket_wrench', 'Socket Wrench'),
    ('soldering_iron', 'Soldering Iron'),
    ('stainless_steel_washer', 'Stainless Steel Washer'),
    ('stainless_steel_wire_brush', 'Stainless Steel Wire Brush'),
    ('staple_gun', 'Staple Gun'),
    ('stud_crimper', 'Stud Crimper'),
    ('stud_finder', 'Stud Finder'),
    ('tape_measure', 'Tape Measure'),
    ('tin_snips', 'Tin Snips'),
    ('traffic_cone', 'Traffic Cone'),
    ('trowel', 'Trowel'),
    ('tubing_cutter', 'Tubing Cutter'),
    ('utility_knife', 'Utility Knife'),
    ('utility_torch', 'Utility Torch'),
    ('voltage_tester_ai', 'Voltage Tester'),
    ('welding_gloves', 'Welding Gloves'),
    ('wheel_barrow', 'Wheelbarrow'),
    ('wirecutter', 'Wire Cutter'),
    ('wrench_ai', 'Wrench');
