-- Road distances from the Bogota warehouse (SHIPPING_LOCATION) fetched once from the Google Routes
-- API on 2026-10-10: the Colombian delivery cities and the 10 major cities of each road country.
-- Seeding them means a fresh or production database starts with the cache filled and never pays
-- Google for these cities again. Existing rows (for example routes staff corrected) are kept.
INSERT INTO shipping_route (country, city_key, city_name, distance_km, source) VALUES
    ('AR', 'salta', 'Salta', 5344.2, 'GOOGLE'),
    ('AR', 'san miguel de tucuman', 'San Miguel de Tucuman', 5635.7, 'GOOGLE'),
    ('AR', 'san juan', 'San Juan', 6180.9, 'GOOGLE'),
    ('AR', 'cordoba', 'Cordoba', 6203.8, 'GOOGLE'),
    ('AR', 'santa fe', 'Santa Fe', 6362.2, 'GOOGLE'),
    ('AR', 'mendoza', 'Mendoza', 6402.4, 'GOOGLE'),
    ('AR', 'rosario', 'Rosario', 6501.7, 'GOOGLE'),
    ('AR', 'buenos aires', 'Buenos Aires', 6796.6, 'GOOGLE'),
    ('AR', 'la plata', 'La Plata', 6854.5, 'GOOGLE'),
    ('AR', 'mar del plata', 'Mar del Plata', 7211.3, 'GOOGLE'),
    ('BO', 'el alto', 'El Alto', 4395.2, 'GOOGLE'),
    ('BO', 'la paz', 'La Paz', 4414.0, 'GOOGLE'),
    ('BO', 'oruro', 'Oruro', 4596.1, 'GOOGLE'),
    ('BO', 'cochabamba', 'Cochabamba', 4748.9, 'GOOGLE'),
    ('BO', 'sacaba', 'Sacaba', 4763.4, 'GOOGLE'),
    ('BO', 'potosi', 'Potosi', 4905.5, 'GOOGLE'),
    ('BO', 'sucre', 'Sucre', 4924.0, 'GOOGLE'),
    ('BO', 'montero', 'Montero', 5163.9, 'GOOGLE'),
    ('BO', 'santa cruz de la sierra', 'Santa Cruz de la Sierra', 5222.0, 'GOOGLE'),
    ('BO', 'tarija', 'Tarija', 5248.5, 'GOOGLE'),
    ('BR', 'manaus', 'Manaus', 3476.8, 'GOOGLE'),
    ('BR', 'brasilia', 'Brasilia', 6881.8, 'GOOGLE'),
    ('BR', 'porto alegre', 'Porto Alegre', 7165.3, 'GOOGLE'),
    ('BR', 'sao paulo', 'Sao Paulo', 7358.5, 'GOOGLE'),
    ('BR', 'belo horizonte', 'Belo Horizonte', 7427.5, 'GOOGLE'),
    ('BR', 'curitiba', 'Curitiba', 7498.7, 'GOOGLE'),
    ('BR', 'fortaleza', 'Fortaleza', 7684.5, 'GOOGLE'),
    ('BR', 'rio de janeiro', 'Rio de Janeiro', 7762.5, 'GOOGLE'),
    ('BR', 'salvador', 'Salvador', 8316.8, 'GOOGLE'),
    ('BR', 'recife', 'Recife', 8788.3, 'GOOGLE'),
    ('CO', 'bogota', 'bogota', 16.1, 'GOOGLE'),
    ('CO', 'villavicencio', 'villavicencio', 112.4, 'GOOGLE'),
    ('CO', 'tunja', 'tunja', 150.3, 'GOOGLE'),
    ('CO', 'ibague', 'ibague', 192.2, 'GOOGLE'),
    ('CO', 'armenia', 'armenia', 268.2, 'GOOGLE'),
    ('CO', 'manizales', 'manizales', 303.2, 'GOOGLE'),
    ('CO', 'neiva', 'neiva', 305.4, 'GOOGLE'),
    ('CO', 'pereira', 'pereira', 307.3, 'GOOGLE'),
    ('CO', 'yopal', 'yopal', 338.1, 'GOOGLE'),
    ('CO', 'bucaramanga', 'bucaramanga', 409.0, 'GOOGLE'),
    ('CO', 'medellin', 'medellin', 427.3, 'GOOGLE'),
    ('CO', 'cali', 'cali', 448.7, 'GOOGLE'),
    ('CO', 'florencia', 'florencia', 543.6, 'GOOGLE'),
    ('CO', 'popayan', 'popayan', 573.3, 'GOOGLE'),
    ('CO', 'cucuta', 'cucuta', 579.5, 'GOOGLE'),
    ('CO', 'monteria', 'monteria', 734.6, 'GOOGLE'),
    ('CO', 'sincelejo', 'sincelejo', 801.5, 'GOOGLE'),
    ('CO', 'pasto', 'pasto', 821.5, 'GOOGLE'),
    ('CO', 'valledupar', 'valledupar', 870.5, 'GOOGLE'),
    ('CO', 'santa marta', 'santa marta', 969.7, 'GOOGLE'),
    ('CO', 'cartagena', 'cartagena', 983.7, 'GOOGLE'),
    ('CO', 'barranquilla', 'barranquilla', 1015.7, 'GOOGLE'),
    ('EC', 'quito', 'Quito', 1099.1, 'GOOGLE'),
    ('EC', 'santo domingo', 'Santo Domingo', 1228.6, 'GOOGLE'),
    ('EC', 'ambato', 'Ambato', 1234.5, 'GOOGLE'),
    ('EC', 'riobamba', 'Riobamba', 1287.8, 'GOOGLE'),
    ('EC', 'portoviejo', 'Portoviejo', 1457.4, 'GOOGLE'),
    ('EC', 'manta', 'Manta', 1475.3, 'GOOGLE'),
    ('EC', 'cuenca', 'Cuenca', 1503.9, 'GOOGLE'),
    ('EC', 'guayaquil', 'Guayaquil', 1505.1, 'GOOGLE'),
    ('EC', 'machala', 'Machala', 1616.5, 'GOOGLE'),
    ('EC', 'loja', 'Loja', 1664.0, 'GOOGLE'),
    ('PE', 'piura', 'Piura', 1916.8, 'GOOGLE'),
    ('PE', 'chiclayo', 'Chiclayo', 2128.2, 'GOOGLE'),
    ('PE', 'trujillo', 'Trujillo', 2337.1, 'GOOGLE'),
    ('PE', 'chimbote', 'Chimbote', 2470.8, 'GOOGLE'),
    ('PE', 'lima', 'Lima', 2895.1, 'GOOGLE'),
    ('PE', 'ica', 'Ica', 3197.7, 'GOOGLE'),
    ('PE', 'huancayo', 'Huancayo', 3197.9, 'GOOGLE'),
    ('PE', 'arequipa', 'Arequipa', 3904.4, 'GOOGLE'),
    ('PE', 'cusco', 'Cusco', 3995.1, 'GOOGLE'),
    ('PE', 'tacna', 'Tacna', 4126.3, 'GOOGLE')
ON CONFLICT (country, city_key) DO NOTHING;
